[package]
name = "nanodlp_format"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
image.workspace = true
png.workspace = true
serde.workspace = true
serde_json.workspace = true
zip.workspace = true
