[package]
name = "ctb_format"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
clap.workspace = true
image.workspace = true
nalgebra.workspace = true

aes = "0.8.4"
cbc = "0.1.2"
sha2 = "0.10.9"

common = { path = "../common" }
