[package]
name = "ctb_format"
version = "0.1.0"
edition = "2024"

[dependencies]
aes.workspace = true
anyhow.workspace = true
cbc.workspace = true
clap.workspace = true
image.workspace = true
nalgebra.workspace = true
sha2.workspace = true

common = { path = "../common" }
